# Generated by CloudCap — FLAT recovery file at repo ROOT.
# Do NOT hand-edit into modules yet; refactor after merge. Bound to live
# infra via the `terraform import` in IMPORT.sh so no resource is recreated.
resource "google_compute_instance" "recovered" {
  name = "cc-chaos-fffbba-cc-public-bucket"
  # Attributes populate on `terraform plan` after import.
  lifecycle { prevent_destroy = true }
}
